(library
 (name test_helper)
 (modules test_helper)
 (libraries neo4j_eio eio eio_main alcotest))

(test
 (name value_test)
 (modules value_test)
 (libraries neo4j_eio alcotest)
 (action (run %{exe:value_test.exe})))

(test
 (name packstream_encode_test)
 (modules packstream_encode_test)
 (libraries neo4j_eio alcotest)
 (action (run %{exe:packstream_encode_test.exe})))

(test
 (name packstream_roundtrip_test)
 (modules packstream_roundtrip_test)
 (libraries neo4j_eio alcotest)
 (action (run %{exe:packstream_roundtrip_test.exe})))

(test
 (name handshake_test)
 (modules handshake_test)
 (libraries neo4j_eio eio eio_main alcotest test_helper)
 (action (run %{exe:handshake_test.exe})))

(test
 (name protocol_classify_test)
 (modules protocol_classify_test)
 (libraries neo4j_eio alcotest)
 (action (run %{exe:protocol_classify_test.exe})))

(test
 (name client_negotiate_test)
 (modules client_negotiate_test)
 (libraries neo4j_eio eio eio_main alcotest test_helper)
 (action (run %{exe:client_negotiate_test.exe})))

(test
 (name protocol_framing_test)
 (modules protocol_framing_test)
 (libraries neo4j_eio eio eio_main alcotest)
 (action (run %{exe:protocol_framing_test.exe})))

(test
 (name auth_test)
 (modules auth_test)
 (libraries neo4j_eio eio eio_main alcotest test_helper)
 (action (run %{exe:auth_test.exe})))

(test
 (name run_query_test)
 (modules run_query_test)
 (libraries neo4j_eio eio eio_main alcotest test_helper)
 (action (run %{exe:run_query_test.exe})))
