(executable
 (name simple_queries)
 (modules simple_queries)
 (libraries neo4j_eio eio eio_main))

(executable
 (name error_handling)
 (modules error_handling)
 (libraries neo4j_eio eio eio_main))

(executable
 (name record_extraction)
 (modules record_extraction)
 (libraries neo4j_eio eio eio_main))

(executable
 (name transactions)
 (modules transactions)
 (libraries neo4j_eio eio eio_main))

(executable
 (name streaming)
 (modules streaming)
 (libraries neo4j_eio eio eio_main))
