(executable
 (name simple_queries)
 (modules simple_queries)
 (libraries neo4j_eio eio eio_main))

(executable
 (name error_handling)
 (modules error_handling)
 (libraries neo4j_eio eio eio_main))

(executable
 (name record_extraction)
 (modules record_extraction)
 (libraries neo4j_eio eio eio_main))

(executable
 (name transactions)
 (modules transactions)
 (libraries neo4j_eio eio eio_main))

(executable
 (name streaming)
 (modules streaming)
 (libraries neo4j_eio eio eio_main))

(executable
 (name temporal_spatial)
 (modules temporal_spatial)
 (libraries neo4j_eio eio eio_main))

(executable
 (name crud)
 (modules crud)
 (libraries neo4j_eio eio eio_main))

(executable
 (name traversal)
 (modules traversal)
 (libraries neo4j_eio eio eio_main))

(executable
 (name batch)
 (modules batch)
 (libraries neo4j_eio eio eio_main unix))
